// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guvekmyuzrcmplblidea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1dmVrbXl1enJjbXBsYmxpZGVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMDYzNDcsImV4cCI6MjA1ODg4MjM0N30.CeAKQu_klI55AEPHiEM4m46xxA7YmuLUGTuQM5u6NKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);